### ISSUE TITLE
Speech Synthesis, festival package not compiled with liquidsoap?

### ISSUE THREAD

**Issue by amavarick** [radiorabe/centos-rpm-liquidsoap#2]
I tried to add speech synthesis to my Icecast server and received the following result when validating my liquidsoap script...

liquidsoap --check ./radio.liq

Could not get a valid media file of kind {audio=2;video=0;midi=0} from "say:Hello, we are currently having some technical difficulties but we'll be back soon so stay tuned!".

According to LiquidSoap documentation:
SAY for speech synthesis (requires festival): say:I am a robot resolves to the WAV file resulting from the synthesis.

I installed festival and festival-dev and that didn't work.  I also uninstalled liquidsoap and resinstalled it and still didn't work.

Would it be correct to say that the festival package was not installed with liquidsoap and that is why it isn't working?  It seems to be consistent with the information I am reading about this.  If not, would you be willing to add it to your packaging?

**Comment by hairmare** [comment]
You may find a list of what was compiled in in the [package description on obs](https://build.opensuse.org/package/show/home:radiorabe:liquidsoap/liquidsoap).

From the output it looks like it might work if you have `festival` and `sox` installed at runtime.

If it needs festival-dev at build time I'd be happy to support that. I'd most likely have to build sox and festival in one of the obs dependency repos on obs though. That might take quite some time and text 2 speech isn't very high on our list since we don't currently have a proper use for it.

Let me know if the runtime install works. If not I'll keep this open to track festival integration.

**Comment by hairmare** [comment]
I was able to get text 2 speech up and running. `liquidsoap-1.2.1-34.1` has the needed changes.

The install was missing the liquidtts script that wraps festival and sox. After failing at getting it to install using make I added a manual install to the specfile.

After `yum install -y festival sox` I tested it with this liquidsoap script.

```
output.file(%wav, "/out/test.wav", single("say:Hello World!"))
```
