### ISSUE TITLE
Several versions in OBS

### ISSUE THREAD

**Issue by spameier** [radiorabe/centos-rpm-liquidsoap#33]
Is it possible to publish several versions in OBS? Currently there is only 1.3.7 available through OBS.

We could use that in [radiorabe/docker-liquidsoap](https://github.com/radiorabe/docker-liquidsoap) to provide several versions for testing [radiorabe/klangbecken](https://github.com/radiorabe/klangbecken).

**Comment by hairmare** [comment]
It would be rather much work to publish multiple versions in OBS. If you need older versions as RPM the easy way to get at them is currently to grab them from our internal Spacewalk Repos. For testing purposes it might make sense to use opam installs since opam makes it easier to install old versions compared with the OBS builds which have to follow rather strict rules.

**Comment by spameier** [comment]
I set up an alpine version covering various releases over at [radiorabe/docker-liquidsoap](https://github.com/radiorabe/docker-liquidsoap).
